version: "3.9"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9001:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
