version: "3.9"
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "3002:3000"
      - "8053:53/tcp"
      - "8053:53/udp"
    volumes:
      - ./work:/opt/adguardhome/work
