scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 've1-proxmox'
    static_configs:
      - targets: ['10.10.0.2:9100']

  - job_name: 've2-proxmox'
    static_configs:
      - targets: ['10.10.0.3:9100']

  - job_name: 'pbs'
    static_configs:
      - targets: ['10.30.0.2:9100']

  - job_name: 'docker-ve2'
    static_configs:
      - targets: ['10.20.0.3:8080']

  - job_name: 'docker-ve1'
    static_configs:
      - targets: ['10.20.0.2:8081']