site_name: Vesta Lab Documentation
site_url: https://vestasec.com
site_author: Ignacio Fernandez
site_description: Technical Lab Documentation – Virtualization, Storage, VPN, Containers, Monitoring

repo_url: https://github.com/iFezGez/labs
repo_name: iFezGez/labs
repo_url: repo_name: https://github.com/iFezGez/labs/vesta-lab
repo_name: iFezGez/labs/vesta-lab

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Lab Setup:
      - Architecture: architecture.md
      - Templates: templates.md
      - Troubleshooting: troubleshooting.md
  - Modules:
      - Network: network.md
      - Virtualization: virtualization.md
      - Storage: storage.md
      - Containers: containers.md
      - Internal Apps: internal_apps.md
      - Monitoring: monitoring.md
      - Backups: backups.md
  - Credits: credits.md


markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

plugins:
  - search
